### ISSUE TITLE
Placeholder in consul plugin section is not resolved

### ISSUE THREAD

**Issue by rafik777** [markround/tiller#59]
**config.d/99_consul.yaml:**
```
data_sources: [  'defaults' , 'file' , 'consul', 'environment' ]
template_sources: [ 'file', 'consul' ]
dynamic_values: true

environments:
  dev:
  qa:

consul:
  url: 'http://consulHost:8500'
  dc: 'dc1'
  templates: "/docker/apps/<%= consul_templates_path %>"
...
```

`consul_templates_path` is set as environment variable

full debug log:
```
$ docker-compose run --rm myapp "tiller -v -d"
tiller v1.2.0 (https://github.com/markround/tiller) <github@markround.com>
Executable: /usr/local/rvm/gems/ruby-2.3.3/gems/tiller-1.2.0/bin/tiller
Loading config file /etc/tiller/config.d/00_base.yaml
Loading config file /etc/tiller/config.d/00_defaults.yaml
Loading config file /etc/tiller/config.d/10_common.yaml
Loading config file /etc/tiller/config.d/10_defaults.yaml
Loading config file /etc/tiller/config.d/10_environments.yaml
Loading config file /etc/tiller/config.d/99_consul.yaml
Using common.yaml v2 format configuration file
Using configuration from /etc/tiller
Using plugins from /usr/local/lib/tiller
Using environment development
Parsing top-level values for ERb syntax
#<DefaultsDataSource:0x00000000f79ef0> : Using values from v2 format common.yaml
#<FileDataSource:0x00000000fa1ef0> : Using values from v2 format common.yaml
#<ConsulDataSource:0x0000000116b948> : Connecting to Consul at http://consulHost:8500
#<ConsulDataSource:0x0000000116b948> : Fetching globals from /docker/apps/globals.yml/all
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/all/cn_host
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/all/cn_profile_base
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/all/db_password
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/all/db_type
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/all/db_user
#<ConsulDataSource:0x0000000116b948> : Fetching per-environment globals from /docker/apps/globals.yml/development
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/development/cn_site
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/development/db_host
#<ConsulDataSource:0x0000000116b948> : Fetching key docker/apps/globals.yml/development/db_name
Template sources loaded [FileTemplateSource, ConsulTemplateSource]
Data sources loaded [DefaultsDataSource, FileDataSource, EnvironmentDataSource, ConsulDataSource]
Dynamic values specified. Will parse all values as ERb.
#<DefaultsDataSource:0x000000015af658> : Using values from v2 format common.yaml
#<DefaultsDataSource:0x000000015aee10> : Using values from v2 format common.yaml
#<FileDataSource:0x000000015ae550> : Using values from v2 format common.yaml
#<FileDataSource:0x000000015adf88> : Using values from v2 format common.yaml
#<ConsulDataSource:0x00000001badfc8> : Connecting to Consul at http://consulHost:8500
#<ConsulDataSource:0x00000001badaf0> : Connecting to Consul at http://consulHost:8500
#<ConsulDataSource:0x00000001badaf0> : Fetching globals from /docker/apps/globals.yml/all
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/all/cn_host
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/all/cn_profile_base
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/all/db_password
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/all/db_type
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/all/db_user
#<ConsulDataSource:0x00000001badaf0> : Fetching per-environment globals from /docker/apps/globals.yml/development
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/development/cn_site
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/development/db_host
#<ConsulDataSource:0x00000001badaf0> : Fetching key docker/apps/globals.yml/development/db_name
#<ConsulTemplateSource:0x00000001ca7a50> : Connecting to Consul at http://consulHost:8500
#<ConsulTemplateSource:0x00000001ca7a50> : Fetching templates from /docker/apps/<%= consul_templates_path %>
/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge': bad URI(is not URI?): /v1/kv//docker/apps/<%= consul_templates_path %> (URI::InvalidURIError)
	from /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/faraday-0.12.1/lib/faraday/connection.rb:415:in `build_exclusive_url'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:192:in `build_env'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/diplomat-1.3.0/lib/diplomat/kv.rb:61:in `get'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/diplomat-1.3.0/lib/diplomat/rest_client.rb:43:in `method_missing'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/tiller-1.2.0/lib/tiller/template/consul.rb:14:in `templates'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/tiller-1.2.0/bin/tiller:160:in `block in <module:Tiller>'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/tiller-1.2.0/bin/tiller:158:in `each'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/tiller-1.2.0/bin/tiller:158:in `<module:Tiller>'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/tiller-1.2.0/bin/tiller:35:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.3/bin/tiller:22:in `load'
	from /usr/local/rvm/gems/ruby-2.3.3/bin/tiller:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by rafik777** [comment]
I found the source of problem finally!
On my problematic environment was one strange env variable (with dots in name):
I added `puts "Error: #{$!}"`
in this section https://github.com/markround/tiller/blob/master/bin/tiller#L122
and the exception was:
`Error: wrong local variable name 'jboss.server.log.dir' for #<Binding:0x00000000e25e00>`
I don't need this env var so I removed this and everything is ok.
But I think that more verbose debug logs would be useful for the future. Especially to log source of exception.
