### ISSUE TITLE
Issue with chown on Ruby 2.5.0

### ISSUE THREAD

**Issue by tgagor** [markround/tiller#74]
Hi, 

I have issue after upgrading from Alpine 3.7 (Ruby 2.4.x) to 3.8 (Ruby 2.5.0) as base for our containers.

```[2018-11-06 08:40:01 +0000] [INFO] Setting ownership/permissions on /opt/service/config/application.properties
/usr/lib/ruby/2.5.0/fileutils.rb:1019:in `fu_get_uid': uninitialized constant FileUtils::Etc (NameError)
	from /usr/lib/ruby/2.5.0/fileutils.rb:967:in `chown'
	from /usr/lib/ruby/gems/2.5.0/gems/tiller-1.4.1/bin/tiller:277:in `block in <module:Tiller>'
	from /usr/lib/ruby/gems/2.5.0/gems/tiller-1.4.1/bin/tiller:175:in `each'
	from /usr/lib/ruby/gems/2.5.0/gems/tiller-1.4.1/bin/tiller:175:in `<module:Tiller>'
	from /usr/lib/ruby/gems/2.5.0/gems/tiller-1.4.1/bin/tiller:35:in `<top (required)>'
	from /usr/bin/tiller:23:in `load'
	from /usr/bin/tiller:23:in `<main>'`
```

In environment file it's plain simple:

```properties.erb:
  target: /opt/service/config/application.properties
  user: root
  group: root
  perms: 0644
  config:
    some_variables: 1
```

File `/opt/service/config/application.properties` exists - by default it have different owner but I tried to change ownership to root and it didn't help.

I resolved issue by removing `user`, `group` parameters. It will work for me this time but it's not a definitive/acceptable solution. I tried to debug it but I was not able to find anything.

**Comment by markround** [comment]
Hmmm. I just added Ruby 2.5 to my Travis automated test builds and I seem to have some other errors with that version of Ruby as well. I'll dig into that and add this issue to some tests. Can't guarantee when I'll have a fix, but thanks for letting me know!

**Comment by EugenMayer** [comment]
Be aware that e.g. ruby2.5 has also issues with diplomat: https://github.com/WeAreFarmGeek/diplomat/issues/171 so there could be quiet some work to have "tiller 2.5 ready"

I also know of other broken libraries. Seems like 2.5 has a "harsher" upgrade path to offer

**Comment by EugenMayer** [comment]
For anybody else, i'am running a fork https://github.com/EugenMayer/tiller which i made compatibly with ruby 3.x - not much more
